name: Docker Image Build & Push

on: push  # Runs this workflow on every push

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on an Ubuntu environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Fetches repository code

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "ishika1108" --password-stdin

      - name: Build Docker Image
        run: docker build -t ishika1108/fastapi-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ishika1108/fastapi-app:latest
